services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: pushkb
      POSTGRES_PASSWORD: pushkb
      POSTGRES_DB: pushkb
    ports:
      - '6543:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: pushkb
      DB_USER: pushkb
      DB_PASSWORD: pushkb
      DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:25.0
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "28080:8060"
    restart: unless-stopped
    networks:
      - local-keycloak

volumes:
  db:
    driver: local

networks:
  local-keycloak:

